"""make_profile_fields_nullable

Revision ID: 065fcd332a65
Revises: 81652f91d3b1
Create Date: 2026-07-19 17:06:56.872234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '065fcd332a65'
down_revision: Union[str, None] = '81652f91d3b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('distributor_profiles', 'cac_registration_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('distributor_profiles', 'tin',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('distributor_profiles', 'owner_full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('distributor_profiles', 'owner_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('distributor_profiles', 'owner_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('distributor_profiles', 'bank_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('distributor_profiles', 'account_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('distributor_profiles', 'account_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('wholesaler_profiles', 'cac_registration_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('wholesaler_profiles', 'tin',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('wholesaler_profiles', 'owner_full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('wholesaler_profiles', 'owner_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('wholesaler_profiles', 'owner_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('wholesaler_profiles', 'bank_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('wholesaler_profiles', 'account_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('wholesaler_profiles', 'account_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wholesaler_profiles', 'account_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('wholesaler_profiles', 'account_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('wholesaler_profiles', 'bank_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('wholesaler_profiles', 'owner_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('wholesaler_profiles', 'owner_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('wholesaler_profiles', 'owner_full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('wholesaler_profiles', 'tin',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('wholesaler_profiles', 'cac_registration_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('distributor_profiles', 'account_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('distributor_profiles', 'account_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('distributor_profiles', 'bank_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('distributor_profiles', 'owner_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('distributor_profiles', 'owner_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('distributor_profiles', 'owner_full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('distributor_profiles', 'tin',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('distributor_profiles', 'cac_registration_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
