"""Added Addtional Fields to Payment Table

Revision ID: 13a8e2c00e23
Revises: 9e870bc468b9
Create Date: 2026-03-31 00:40:56.916079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '13a8e2c00e23'
down_revision: Union[str, None] = '9e870bc468b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('order_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('payments', sa.Column('wholesaler_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'wholesaler_name')
    op.drop_column('payments', 'order_number')
    # ### end Alembic commands ###
