"""Changed payment_method field on payment table to string type

Revision ID: 1f83e2730071
Revises: 13a8e2c00e23
Create Date: 2026-03-31 01:38:39.867668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f83e2730071'
down_revision: Union[str, None] = '13a8e2c00e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'payment_method',
               existing_type=postgresql.ENUM('BANK_TRANSFER', name='paymentmethod'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'payment_method',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('BANK_TRANSFER', name='paymentmethod'),
               existing_nullable=False)
    # ### end Alembic commands ###
