"""Add subaccount_code field to Distributor table

Revision ID: 4734156992e8
Revises: 5a53b863d69d
Create Date: 2026-03-28 03:32:39.207278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4734156992e8'
down_revision: Union[str, None] = '5a53b863d69d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributor_profiles', sa.Column('subaccount_code', sa.String(), server_default='', nullable=False))
    op.drop_column('users', 'subaccount_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subaccount_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('distributor_profiles', 'subaccount_code')
    # ### end Alembic commands ###
