"""Changed the distributor_id to use the User table when connecting to the Payment table

Revision ID: 4f4a32d860cd
Revises: d9e417be19c2
Create Date: 2026-03-31 02:20:24.591884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4f4a32d860cd'
down_revision: Union[str, None] = 'd9e417be19c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'distributor_profile_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'distributor_profile_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
