"""Add subaccount_code field to User table for distributors

Revision ID: 5a53b863d69d
Revises: d87f9efd071a
Create Date: 2026-03-28 03:15:13.132413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5a53b863d69d'
down_revision: Union[str, None] = 'd87f9efd071a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subaccount_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subaccount_code')
    # ### end Alembic commands ###
