"""add wallet and dimensions and dedicated account details

Revision ID: 81652f91d3b1
Revises: 46ae0afa4e64
Create Date: 2026-07-16 18:02:25.658324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '81652f91d3b1'
down_revision: Union[str, None] = '46ae0afa4e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributor_profiles', sa.Column('paystack_dedicated_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('distributor_profiles', sa.Column('is_bank_active', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('products', sa.Column('dimensions', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('wholesaler_profiles', sa.Column('paystack_dedicated_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wholesaler_profiles', 'paystack_dedicated_account_id')
    op.drop_column('products', 'weight')
    op.drop_column('products', 'dimensions')
    op.drop_column('distributor_profiles', 'is_bank_active')
    op.drop_column('distributor_profiles', 'paystack_dedicated_account_id')
    # ### end Alembic commands ###
