"""Removed Unecessary fields from Payment tablr

Revision ID: 9e870bc468b9
Revises: 9b7ce9233aa7
Create Date: 2026-03-31 00:36:30.375758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e870bc468b9'
down_revision: Union[str, None] = '9b7ce9233aa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('payments_verified_by_id_fkey'), 'payments', type_='foreignkey')
    op.drop_column('payments', 'rejected_at')
    op.drop_column('payments', 'proof_image_url')
    op.drop_column('payments', 'approved_at')
    op.drop_column('payments', 'verified_at')
    op.drop_column('payments', 'rejection_reason')
    op.drop_column('payments', 'bank_details')
    op.drop_column('payments', 'verified_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('verified_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('bank_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('rejection_reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('proof_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('rejected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('payments_verified_by_id_fkey'), 'payments', 'users', ['verified_by_id'], ['id'])
    # ### end Alembic commands ###
