"""Updates some stuff in the payment table

Revision ID: b0b1edd8a926
Revises: 4f4a32d860cd
Create Date: 2026-03-31 02:37:39.742594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b0b1edd8a926'
down_revision: Union[str, None] = '4f4a32d860cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('distributor_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_payments_distributor_profile_id'), table_name='payments')
    op.create_index(op.f('ix_payments_distributor_id'), 'payments', ['distributor_id'], unique=False)
    op.drop_constraint(op.f('payments_distributor_profile_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', ['distributor_id'], ['id'])
    op.drop_column('payments', 'distributor_profile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('distributor_profile_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_distributor_profile_id_fkey'), 'payments', 'distributor_profiles', ['distributor_profile_id'], ['id'])
    op.drop_index(op.f('ix_payments_distributor_id'), table_name='payments')
    op.create_index(op.f('ix_payments_distributor_profile_id'), 'payments', ['distributor_profile_id'], unique=False)
    op.drop_column('payments', 'distributor_id')
    # ### end Alembic commands ###
