"""Add category table and relationship

Revision ID: c987603e8668
Revises: d3bf3fdda524
Create Date: 2026-02-17 23:51:25.068932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c987603e8668'
down_revision: Union[str, None] = 'd3bf3fdda524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Column already exists in database, skipping
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Column already exists in database, skipping
    pass
    # ### end Alembic commands ###
