"""Fix delivery fields in orders table

Revision ID: d87f9efd071a
Revises: c987603e8668
Create Date: 2026-03-23 15:29:19.563462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd87f9efd071a'
down_revision: Union[str, None] = 'c987603e8668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_address', sa.String(), server_default='', nullable=False))
    op.add_column('orders', sa.Column('is_delivery', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('orders', sa.Column('contact_name', sa.String(), server_default='', nullable=False))
    op.add_column('orders', sa.Column('contact_phone_no', sa.String(), server_default='', nullable=False))
    op.add_column('orders', sa.Column('delivery_instructions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_instructions')
    op.drop_column('orders', 'contact_phone_no')
    op.drop_column('orders', 'contact_name')
    op.drop_column('orders', 'is_delivery')
    op.drop_column('orders', 'delivery_address')
    # ### end Alembic commands ###
