"""Added a relationship between the payment and distributor_profile table

Revision ID: d9e417be19c2
Revises: 1f83e2730071
Create Date: 2026-03-31 01:58:34.786685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd9e417be19c2'
down_revision: Union[str, None] = '1f83e2730071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('distributor_profile_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_payments_distributor_profile_id'), 'payments', ['distributor_profile_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'distributor_profiles', ['distributor_profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_distributor_profile_id'), table_name='payments')
    op.drop_column('payments', 'distributor_profile_id')
    # ### end Alembic commands ###
